version: '3.2'

services:
  db:
    image: postgres:16.0-bullseye
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      POSTGRES_USER: user
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - 5000:5000